modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="asdlab"
version="1.0.0"
displayName="ASDLab"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="DEVRAN, MCreator"

[[dependencies.asdlab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.asdlab]]
    modId="grimmscraft"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


